# Dockerfile.frontend
FROM nginx:alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

ARG ANGULAR_BUILD_DIR

COPY ${ANGULAR_BUILD_DIR}/ ./

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]